# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  paschoalottodesafioapi:
    image: paschoalottodesafioapi
    build:
      context: .
      dockerfile: Paschoalotto.Desafio.Api/Dockerfile
    ports:
      - 5275:8080
  paschoalottodesafioweb:
    image: paschoalottodesafioweb
    build:
      context: Paschoalotto.Desafio.Web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4173:4173
