version: "3.4"

networks:
  database:

volumes:
  data:

services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "!desafio@1234#"
      POSTGRES_DB: desafio_paschoalotto
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - database

  paschoalottodesafioapi:
    image: paschoalottodesafioapi
    build:
      context: .
      dockerfile: Paschoalotto.Desafio.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5275:5275
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DESAFIODB_CONNECTION_STRING="Username=postgres;Password=!desafio@1234#;Host=database;Database=desafio_paschoalotto;"
    depends_on:
      - database
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
